--[[
	TRACK LIST FORMAT

	TITLE: STRING
	LENGTH: {MINUTES: NUMBER; SECONDS: NUMBER}
	BPM: NUMBER,
	KEY: STRING (CAMELOT SYSTEM)
	COVER: IMAGE ID
--]]

return {
	{title = "Obskür - Bayside", length = {minutes = 5, seconds = 29}, bpm = 125, key = "3B", cover = "rbxassetid://99767365149819"},
	{title = "Cave Studio - Shake The Dice (PEACE MAKER! REMIX)", length = {minutes = 3, seconds = 6}, bpm = 129, key = "9B", cover = "rbxassetid://125953616558170"},
	{title = "PAX - SNAKE", length = {minutes = 3, seconds = 1}, bpm = 127, key = "9B", cover = "rbxassetid://99681210519769"},
	{title = "Heider, GIANT, Moosa Saleem - Like A Tap", length = {minutes = 3, seconds = 36}, bpm = 128, key = "11B", cover = "rbxassetid://80029718287407"},
	{title = "JOSH - Feel That Way", length = {minutes = 2, seconds = 31}, bpm = 128, key = "1B", cover = "rbxassetid://95902775520846"},
	{title = "PRMGH - Signs", length = {minutes = 2, seconds = 32}, bpm = 128, key = "7A", cover = "rbxassetid://99796716534048"},
	{title = "Mau P - Gimme That Bounce", length = {minutes = 3, seconds = 37}, bpm = 126, key = "4B", cover = "rbxassetid://92268648133860"},
	{title = "Club Angel - Cry", length = {minutes = 3, seconds = 50}, bpm = 142, key = "9A", cover = "rbxassetid://116306695804788"},
	{title = "Odd Mob - LEFT TO RIGHT", length = {minutes = 2, seconds = 26}, bpm = 128, key = "4B", cover = "rbxassetid://109550275509310"},
	{title = "Boris Brejcha - Welcome To Real Life", length = {minutes = 7, seconds = 43}, bpm = 125, key = "8B", cover = "rbxassetid://108535667117187"},
	{title = "SWACQ - No Strings Attached", length = {minutes = 3, seconds = 2}, bpm = 124, key = "10B", cover = "rbxassetid://133219485935384"},
	{title = "Mike Cervello & Curbi - Deja Vu", length = {minutes = 3, seconds = 6}, bpm = 126, key = "11B", cover = "rbxassetid://92633128639893"},
	{title = "Sebastian Ingrosso, Steve Angello - Skip", length = {minutes = 2, seconds = 32}, bpm = 132, key = "9B", cover = "rbxassetid://84100379781587"},
	{title = "Skrillex, Noisia, josh pan & Dylan Brady - Supersonic", length = {minutes = 2, seconds = 45}, bpm = 172, key = "8A", cover = "rbxassetid://79938067563944"},
	{title = "beastboi. - SHAPESHIFTERZ", length = {minutes = 2, seconds = 38}, bpm = 121, key = "3A", cover = "rbxassetid://131713122579834"},
	{title = "AlunaGeorge & Kaytranada - Kaleidoscope Love", length = {minutes = 5, seconds = 49}, bpm = 115, key = "9A", cover = "rbxassetid://112980727578098"},
}